add nice-password-validator
Recursyve/nice_flutter_kit pull request #16
Opened 2022-03-07 15:33 UTC by samuelgirardpaquet

2022-03-07 15:49 UTC, Jtplouffe commented on lib/src/widgets/nice-password-validator.widget.dart
> +  List<Widget> _buildValidations(MapEntry<RegExp, String> entry) {
Ça serait mieu que cette méthode retourne la row au lieu de retourné une liste de widget

2022-03-07 16:19 UTC, Gabrielbdry requested changes

2022-03-07 16:19 UTC, Gabrielbdry commented on lib/src/widgets/nice-password-validator.widget.dart
> +  final Map<RegExp, String> validationsAndTranslationsMap;
validationsAndTranslations

Pas besoin de spécifier que c'est une map anyways c'est le type

2022-03-07 16:19 UTC, Gabrielbdry commented on lib/src/widgets/nice-password-validator.widget.dart
> +class PasswordValidator extends StatelessWidget {
On pourrait pt faire un ReactivePasswordValidator qui s'occupe de listen pour le password avec un formControlName? Mais dans un widget séparé.

@Jtplouffe

2022-03-25 03:48 UTC, Gabrielbdry approved these changes

2022-03-25 03:48 UTC, Gabrielbdry commented on lib/src/widgets/nice-password-validator.widget.dart
> +class ReactiveCheckListValidator extends StatelessWidget {
Checklist

Aussi le nom du fichier est pas bon

2022-03-25 11:46 UTC, Jtplouffe approved these changes

2022-03-25 11:46 UTC, Jtplouffe commented on lib/src/widgets/nice-password-validator.widget.dart
> +import 'package:flutter/material.dart';
Je pense qu'on ne devrait pas avoir `nice` comme préfix de nom de fichier, ça fait trop redontant, surtout que dans le project on n'importe pas directement ce fichier, mais le fichier `package:nice_flutter_kit/nice_flutter_kit.dart`.

2022-03-25 11:46 UTC, Jtplouffe commented on lib/src/widgets/nice-password-validator.widget.dart
> +            validationsAndTranslations.entries.length > 0, "validationsAndTranslations must contains at least 1 entry"),
```suggestion
            validationsAndTranslations.entries.isNotEmpty, "validationsAndTranslations must contains at least 1 entry"),
```

2022-03-25 15:05 UTC, merged