Création de compte
Recursyve/nice_flutter_kit pull request #17
Opened 2022-03-17 16:21 UTC by Jtplouffe

Ajout de `NiceAccountCreation`

Closes #4 

Ce widget permet de beaucoup simplifier le flow de création de compte.
Beaucoup de configuration peuvent être passé au widget avec un `NiceAccountCreationConfig`.

## NiceAccountCreationBasePage
Chaque page du `NiceAccountCreation` doit extend `NiceAccountCreationBasePage` et implémenter la méthode `buildPage(BuildContext context)`.

Il y a plusieurs implémentation de page dans la lib:
- `NiceAccountCreationLayoutPage`: Implémentation abstraite qui rajoute la possibilité d'avoir un titre et un sous-titre avec un alignement + scrolling du contenue. On peu passé un `NiceAccountCreationPageConfig` qui permet de définir le style et alignement pour la page. Si ce n'est pas passé, on fallback sur le `NiceAccountCreationConfig#defaultPageConfig`. Le titre / sous-titre doit être passé avec un `NiceAccountCreationLayoutHeaderData`. Cette classe permet l'utilisé directement de `String` ou avec un `builder`.
- `NiceAccountCreationContentPage`: Permet de créer une page via un widget. Cette page `extends` `NiceAccountCreationLayoutPage`, donc elle peu avoir un titre / sous-titre et un alignement du contenue.
- `NiceAccountCreationContentBuilderPage`: Même principe que `NiceAccountCreationContentPage`, mais avec un `callback` au lieu d`un `widget`.
- `NiceAccountCreationEmailPage`: Page d'entré de courriel + confirmation de courriel. On lui passe un `formControlName`, et les inputs et validations sont gérés. Basé sur `NiceAccountCreationLayoutPage`, donc on peu passé title / sous-title et alignement.
- `NiceAccountCreationPasswordPage`: Même principe que `NiceAccountCreationEmailPage`, mais pour le mot de passe.

<br>

Le `NiceAccountCreationBasePage` contient 2 donné membre, soit `enabledStrategy` et `validationStrategy`;

## NiceAccountCreationBaseEnabledStrategy
Intecface permettant de déterminé si une page est enabled (fait parti du PageView)
Cela est pratique si, par exemple, on veut skip certaine page selon une condition.

Il y a 2 implémentations dans la lib, et le project pourrait en implémenter d'autre si besoin

- `NiceAccountCreationAlwaysEnabledEnabledStrategy`: Page toujours active
- `NiceAccountCallbackEnabledStrategy`: Utilise un callback pour savoir si la page est active

## NiceAccountCreationBaseValidationStrategy
Interfare permettant de déterminé si une page est valide
La méthode `isValid` est appelé sur la page active quand on appui sur le bouton next.

Il y a 2 implémentations dans la lib, et le project pourrait en implémenter d'autre si besoin

- `AccountCreationAlwaysValidValidationStrategy`: Page toujours valide, pratique pour une page de présentation / intro.
- `NiceAccountCreationFormGroupValidationStrategy`: Validation basé sur `ReactiveForms`. Par défaut la méthode `markAllAsTouched` va être appelé si ce n'est pas valide. Peu être désactiver avec `markAllAsTouchedIfInvalid`.

<br>

J'ai modifié l'exemple pour permettre de mieux démo les widgets.
J'ai aussi ajouté le widget `NiceAutomaticUnfocus`.

<br>

https://user-images.githubusercontent.com/32107801/158842717-ee8c1b94-32e8-4587-946c-2c9b7df0cd7b.mov

2022-03-22 01:14 UTC, JulienDuf approved these changes
Très nice! Pour le versionnement, je mettrais la nouvelle version à 1.0.0 parce que ce n'est une patch, c'est une nouvelle fonctionnalité

2022-03-22 13:42 UTC, richerarc approved these changes

2022-03-22 20:19 UTC, Gabrielbdry requested changes
Commentaire d'ordre plus général, ce que tu as fait pourrait être réutiliser dans bien d'autres contextes qu'à l'inscription j'ai l'impression, en fait il n'y a pas vraiment de lien avec un conception d'inscription sauf pour les pages de base de courriel/mot de passe.

Ça vaudrait peut-être la peine de refactor les noms pour que ce soit plus un fullscreen stepper?

Pour te donner un exemple, dans le cas où nous aurions une application dans laquelle on veut faire un quiz spontanné sur le sport (rip), on pourrait probablement réutiliser ça.

Faudrait juste trouver un nom approprié si c'est quelque chose que tu crois qui pourrait être fait.

NicePageViewForm?

2022-03-22 20:19 UTC, Gabrielbdry commented on example/lib/pages/account-creation.page.dart
> +            NiceAccountCreationEmailPage(
Du point de vue d'utilisateur de cette api, il n'y aurait pas eu moyen de faire des factory constructor? Par exemple NiceAccountCreationPage.custom, NiceAccountCreationPage.email, NiceAccountCreationPage.password?

2022-03-22 20:19 UTC, Gabrielbdry commented on lib/src/account-creation/account-creation.widget.dart
> +    }
Ça me semble plus safe de faire ça?
```suggestion
    if (_localPageController != null) {
      // Only dispose of the PageController if it was created by this widget
      _localPageController.dispose();
    }
```

2022-03-22 20:19 UTC, Gabrielbdry commented on lib/src/account-creation/account-creation.widget.dart
> +  late final _localPageController;
```suggestion
  late final PageController _localPageController;
```

2022-03-23 12:06 UTC, richerarc approved these changes

2022-03-23 12:12 UTC, Jtplouffe commented on example/lib/pages/account-creation.page.dart
> +            NiceAccountCreationEmailPage(
Oui, on peu faire de la redirection de constructeur. Le user va toujours pouvoir créer des page à partir des class, ou utilisé les factories. Le seul désavantage est que le page ne peuvent plus  être `cosnt`, mais étant donné qu'il ne va surment pas avoir 100 pages, ça ne risque pas de changé grand chose

![image](https://user-images.githubusercontent.com/32107801/159696219-b6f4aab8-6c26-499e-9b3a-339f1360f8be.png)
![image](https://user-images.githubusercontent.com/32107801/159696309-c34624c5-0d74-4e10-8435-f603eabb7a3c.png)

2022-03-23 12:17 UTC, Jtplouffe commented
Oups 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/32107801/159696979-7b5c6fde-50cd-48b6-88a2-a0b442910b26.png">

Le commentaire était pas rapport au dispose du page view controller, que j'ai fix

2022-03-23 12:20 UTC, Jtplouffe commented
> Commentaire d'ordre plus général, ce que tu as fait pourrait être réutiliser dans bien d'autres contextes qu'à l'inscription j'ai l'impression, en fait il n'y a pas vraiment de lien avec un concept d'inscription sauf pour les pages de base de courriel/mot de passe.
> 
> Ça vaudrait peut-être la peine de refactor les noms pour que ce soit plus un fullscreen stepper?
> 
> Pour te donner un exemple, dans le cas où nous aurions une application dans laquelle on veut faire un quiz spontanné sur le sport (rip), on pourrait probablement réutiliser ça.
> 
> Faudrait juste trouver un nom approprié si c'est quelque chose que tu crois qui pourrait être fait.
> 
> NicePageViewForm?

Effectivement, ça pourrait servir à beaucoup plus de chose que juste de la création de compte, mais je ne suis vraiment pas sûr pour le nom, car çe n'est pas necessairement un Form (les seules page qui on un concept de form est email / password et leurs validation)

2022-03-24 18:05 UTC, merged