fix back from onboarding.
Recursyve/nice_flutter_kit pull request #36
Opened 2022-10-18 16:18 UTC by MacChab

Pour pop quand on back avec le bouton back de la premiere page du onboarding.

2022-10-19 11:44 UTC, Jtplouffe requested changes

2022-10-19 11:44 UTC, Jtplouffe commented on lib/src/page-view-form/widgets/page-view-form-buttons.widget.dart
> +                  }
Le formatage n'est pas bon

2022-10-20 21:15 UTC, Gabrielbdry approved these changes

2022-10-21 11:34 UTC, Jtplouffe approved these changes

2022-10-21 11:34 UTC, merged

2022-10-21 11:38 UTC, Jtplouffe commented
@MacChab C'est déployer, `nice_flutter_kit: 1.4.13`