Add loading opacity in NiceBaseListLoading
Recursyve/nice_flutter_kit pull request #51
Opened 2023-05-03 15:57 UTC by ClovisProvost

Withe LoadingOpacity = 0:

https://user-images.githubusercontent.com/110677145/235971148-c92b67f0-2998-46a0-955f-ee753f35371d.mp4

2023-05-03 15:58 UTC, Jtplouffe commented on lib/src/base-list/widgets/base-list-loading-indicator.widget.dart
> +    this.loadingOpacity = 1,
On serait mieux de le mettre a `0` par défaut, sinon c'est un breaking changes.

2023-05-03 15:59 UTC, Gabrielbdry requested changes

2023-05-03 15:59 UTC, Gabrielbdry commented on lib/src/base-list/widgets/base-list-loading-indicator.widget.dart
> +        opacity: loadingOpacity,
C'est pour l'opacité du spinner ou de ce qui est affiché en dessous? Si c'est pour cacher le empty state je ne suis pas certain que ce soit la meilleure approche.

2023-05-03 17:35 UTC, ClovisProvost commented on lib/src/base-list/widgets/base-list-loading-indicator.widget.dart
> +    this.loadingOpacity = 1,
Le NiceLoadingOverlay utilise 1 par défaut donc c'est pour avoir la même chose.

2023-05-03 17:41 UTC, ClovisProvost commented on lib/src/base-list/widgets/base-list-loading-indicator.widget.dart
> +        opacity: loadingOpacity,
C'est pour l'opacité du child. C'est comme ça que fonctionne le NiceLoadingOverlay. Est-ce que ça serait mieux de faire:
```dart
        if (state.loading) {
          return NiceLoadingOverlay(
            color: color,
            size: size,
            lineWidth: lineWidth,
            opacity: loadingOpacity,
          );
        }
        return child;
```
Il faudrait aussi faire en sorte de pouvoir afficher `child` pendant le loading avec un paramètre. Lequel serait le mieux?

2023-05-03 19:11 UTC, Gabrielbdry commented on lib/src/base-list/widgets/base-list-loading-indicator.widget.dart
> +        opacity: loadingOpacity,
@ClovisProvost Idéalement le widget devrait pouvoir supporter l'opacité, mon point c'est plus qu'il y a une distinction entre opacité et visibilité. Si c'est une question de visible et pas visible, tu peux utiliser le widget Visibility.

2023-05-03 21:05 UTC, ClovisProvost commented on lib/src/base-list/widgets/base-list-loading-indicator.widget.dart
> +        opacity: loadingOpacity,
Ça a de l'allure, donc ça serait de modifier le NiceLoadingOverlay pour le utiliser le widget visibility?

2023-05-05 13:08 UTC, ClovisProvost commented
J'ai modifier le NiceLoadingOverlay pour utiliser un Visibility. Est-ce que ça de l'allure ? @Gabrielbdry @Jtplouffe

2023-05-05 13:51 UTC, Gabrielbdry commented on lib/src/widgets/nice-loading-overlay.widget.dart
>    final double opacity;
Tu peux renommer absorb et opacity pour suivre le même pattern?

childLoadingOpacity et childAbsorb

2023-05-05 13:53 UTC, Jtplouffe commented on lib/src/widgets/nice-loading-overlay.widget.dart
>    final double opacity;
Il faudrait plutôt ajouter de nouvelle fields, et deprecated les anciens pour éviter de faire des breaking changes

2023-05-08 12:37 UTC, Jtplouffe approved these changes

2023-05-08 12:37 UTC, Jtplouffe commented on lib/src/widgets/nice-loading-overlay.widget.dart
> +              visible: childLoadingVisibility ? true : !loading,
```suggestion
              visible: childLoadingVisibility || !loading,
```

2023-05-10 16:28 UTC, merged