Refactor NiceBaseList
Recursyve/nice_flutter_kit pull request #9
Opened 2022-02-08 20:11 UTC by gabaudette

## Voici les changements appliqués pour la NiceBaseList

1. J'ai fait en sorte que le **title** ne soit pas _required_ car ça peut amener une certaine confusion si on est en mobile (le **title** n'apparait pas en mobile.)
2. J'ai fait en sorte que le padding (mobile et large) soit modifiable,  les paddings actuels sont maintenant les paddings par défaut.
3. J'ai ajouté la possibilité de retirer la barre de recherche

2022-02-08 20:23 UTC, Gabrielbdry requested changes

2022-02-08 20:23 UTC, Gabrielbdry commented on lib/src/widgets/base-list/widgets/nice-base-list-header.widget.dart
> +        if (!hideSearch) _buildSearch(),
Faudrait faire comme le code au-dessus, au lieu de faire un space-between, faire deux expanded et mettre un Align left pour le titre et right pour le search.

2022-02-08 23:32 UTC, Gabrielbdry approved these changes

2022-02-09 12:32 UTC, Jtplouffe approved these changes

2022-02-09 12:32 UTC, Jtplouffe commented on lib/src/widgets/base-list/widgets/nice-base-list-header.widget.dart
> +          title ?? const SizedBox.shrink(),
```suggestion
          if (title != null) title,
```

2022-02-09 13:55 UTC, merged